spring.application.name=SpringJDBCDemo
spring.datasource.url=jdbc:postgresql://localhost:5433/StudentDB
spring.datasource.username=postgres
spring.datasource.password=Surendar@2002
spring.datasource.driver-class-name=org.postgresql.Driver
