spring.application.name=AIDocumentAnalyzer

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/ai_doc_analyzer
spring.datasource.username=postgres
spring.datasource.password=Surendar@2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# AI Configuration
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3

