spring.application.name=AIDocumentAnalyzer

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/ai_doc_analyzer
spring.datasource.username=postgres
spring.datasource.password=Surendar@2002

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# AI Configuration

#spring.ai.openai.api-key=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
#spring.ai.openai.chat.options.model=gpt-4o-mini

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3

#spring.servlet.multipart.enabled=true
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB